package models

const (
	SEGMENT_COL                      = "segment"
	ITEM_ID                          = "_id"
	ITEM_CREATE_TIME                 = "createdAt"
	ITEM_UPDATA_TIME                 = "updatedAt"
	SEGMENT_ITEM_MARK                = "mark"
	SEGMENT_ITEM_FRAGMENT_START_TIME = "fragmentstarttime"
	SEGMENT_ITEM_START_TIME          = "starttime"
	SEGMENT_ITEM_END_TIME            = "endtime"
	SEGMENT_ITEM_FILE_NAME           = "filename"
	SEGMENT_ITEM_EXPIRE              = "expireAt"
	UA_COL                           = "ua"
	UA_ITEM_UID                      = "uid"
	UA_ITEM_UAID                     = "uaid"
	UA_ITEM_NAMESPACE                = "namespace"
	UA_ITEM_PASSWORD                 = "password"
	UA_ITEM_VOD                      = "vod"
	UA_ITEM_LIVE                     = "live"
	UA_ITEM_ONLINE                   = "online"
	UA_ITEM_EXPIRE                   = "expire"
	USER_COL                         = "user"
	USER_UUID                        = "uid"
	USER_PASSWORD                    = "password"
	USER_STATUS                      = "status"
	USER_REGTIME                     = "registertime"
	USER_IS_SUPERUSER                = "issuperuser"
	NAMESPACE_COL                    = "namespace"
	NAMESPACE_ITEM_ID                = "namespace"
	NAMESPACE_ITEM_BUCKET            = "bucket"
	NAMESPACE_ITEM_UID               = "uid"
	NAMESPACE_ITEM_DOMAIN            = "domain"
	NAMESPACE_ITEM_AUTO_CREATE_UA    = "auto"
	NAMESPACE_ITEM_EXPIRE            = "expire"
)
