sudo: true
language: go
go:
  - 1.10.1
addons:
  apt:
    sources:
      - mongodb-3.2-precise
    packages:
      - mongodb-org-server
      - mongodb-org-shell
services:
  - mongodb
install:
  - sleep 10
script:
  - source env.sh
  - echo $GOPATH
  - echo "TRAVIS_BRANCH=" $TRAVIS_BRANCH
  - cd ./link/vod/src; curl https://aone.qiniu.io/api/coverage/collect?token=A59B8029-E9A1-4FF3-B72B-3657CEAC64D4 | bash
  - cd ..; make style
