sudo: true
language: go
go:
  - 1.10.1
addons:
  apt:
    sources:
      - mongodb-3.2-precise
    packages:
      - mongodb-org-server
      - mongodb-org-shell
services:
  - mongodb
  - redis
install:
  - sleep 10
script:
  - source env.sh
  - echo $GOPATH
  - echo "TRAVIS_BRANCH=" $TRAVIS_BRANCH
  - if [[ $TRAVIS_BRANCH == "dev-merge" || $TRAVIS_BRANCH == "master" ]]; then cd src/qiniu.com/linking; curl https://aone.qiniu.io/api/coverage/collect?token=A59B8029-E9A1-4FF3-B72B-3657CEAC64D4 | bash; else cd src/qiniu.com/linking; go test -v ./...; fi
  - make gofmt-check
  - make govet-check
