# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.11

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.11.1/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.11.1/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/edgar/work/github/linking

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/edgar/work/github/linking

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.11.1/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.11.1/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/edgar/work/github/linking/CMakeFiles /Users/edgar/work/github/linking/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/edgar/work/github/linking/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ffmpeg

# Build rule for target.
ffmpeg: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ffmpeg
.PHONY : ffmpeg

# fast build rule for target.
ffmpeg/fast:
	$(MAKE) -f third_party/CMakeFiles/ffmpeg.dir/build.make third_party/CMakeFiles/ffmpeg.dir/build
.PHONY : ffmpeg/fast

#=============================================================================
# Target rules for targets named curl-7.61.0

# Build rule for target.
curl-7.61.0: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 curl-7.61.0
.PHONY : curl-7.61.0

# fast build rule for target.
curl-7.61.0/fast:
	$(MAKE) -f third_party/CMakeFiles/curl-7.61.0.dir/build.make third_party/CMakeFiles/curl-7.61.0.dir/build
.PHONY : curl-7.61.0/fast

#=============================================================================
# Target rules for targets named pjsip

# Build rule for target.
pjsip: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pjsip
.PHONY : pjsip

# fast build rule for target.
pjsip/fast:
	$(MAKE) -f third_party/CMakeFiles/pjsip.dir/build.make third_party/CMakeFiles/pjsip.dir/build
.PHONY : pjsip/fast

#=============================================================================
# Target rules for targets named vod

# Build rule for target.
vod: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vod
.PHONY : vod

# fast build rule for target.
vod/fast:
	$(MAKE) -f link/CMakeFiles/vod.dir/build.make link/CMakeFiles/vod.dir/build
.PHONY : vod/fast

#=============================================================================
# Target rules for targets named sip-x86_64-unknown-linux-gnu

# Build rule for target.
sip-x86_64-unknown-linux-gnu: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sip-x86_64-unknown-linux-gnu
.PHONY : sip-x86_64-unknown-linux-gnu

# fast build rule for target.
sip-x86_64-unknown-linux-gnu/fast:
	$(MAKE) -f link/libsip/CMakeFiles/sip-x86_64-unknown-linux-gnu.dir/build.make link/libsip/CMakeFiles/sip-x86_64-unknown-linux-gnu.dir/build
.PHONY : sip-x86_64-unknown-linux-gnu/fast

#=============================================================================
# Target rules for targets named max_account-x86_64-unknown-linux-gnu

# Build rule for target.
max_account-x86_64-unknown-linux-gnu: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 max_account-x86_64-unknown-linux-gnu
.PHONY : max_account-x86_64-unknown-linux-gnu

# fast build rule for target.
max_account-x86_64-unknown-linux-gnu/fast:
	$(MAKE) -f link/libsip/test/max_account/CMakeFiles/max_account-x86_64-unknown-linux-gnu.dir/build.make link/libsip/test/max_account/CMakeFiles/max_account-x86_64-unknown-linux-gnu.dir/build
.PHONY : max_account-x86_64-unknown-linux-gnu/fast

#=============================================================================
# Target rules for targets named max_call_uas-x86_64-unknown-linux-gnu

# Build rule for target.
max_call_uas-x86_64-unknown-linux-gnu: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 max_call_uas-x86_64-unknown-linux-gnu
.PHONY : max_call_uas-x86_64-unknown-linux-gnu

# fast build rule for target.
max_call_uas-x86_64-unknown-linux-gnu/fast:
	$(MAKE) -f link/libsip/test/max_call/uas/CMakeFiles/max_call_uas-x86_64-unknown-linux-gnu.dir/build.make link/libsip/test/max_call/uas/CMakeFiles/max_call_uas-x86_64-unknown-linux-gnu.dir/build
.PHONY : max_call_uas-x86_64-unknown-linux-gnu/fast

#=============================================================================
# Target rules for targets named max_call_uac-x86_64-unknown-linux-gnu

# Build rule for target.
max_call_uac-x86_64-unknown-linux-gnu: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 max_call_uac-x86_64-unknown-linux-gnu
.PHONY : max_call_uac-x86_64-unknown-linux-gnu

# fast build rule for target.
max_call_uac-x86_64-unknown-linux-gnu/fast:
	$(MAKE) -f link/libsip/test/max_call/uac/CMakeFiles/max_call_uac-x86_64-unknown-linux-gnu.dir/build.make link/libsip/test/max_call/uac/CMakeFiles/max_call_uac-x86_64-unknown-linux-gnu.dir/build
.PHONY : max_call_uac-x86_64-unknown-linux-gnu/fast

#=============================================================================
# Target rules for targets named max_ongoing_uas

# Build rule for target.
max_ongoing_uas: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 max_ongoing_uas
.PHONY : max_ongoing_uas

# fast build rule for target.
max_ongoing_uas/fast:
	$(MAKE) -f link/libsip/test/max_ongoning_call_for_account/uas/CMakeFiles/max_ongoing_uas.dir/build.make link/libsip/test/max_ongoning_call_for_account/uas/CMakeFiles/max_ongoing_uas.dir/build
.PHONY : max_ongoing_uas/fast

#=============================================================================
# Target rules for targets named max_ongoing_uac-x86_64-unknown-linux-gnu

# Build rule for target.
max_ongoing_uac-x86_64-unknown-linux-gnu: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 max_ongoing_uac-x86_64-unknown-linux-gnu
.PHONY : max_ongoing_uac-x86_64-unknown-linux-gnu

# fast build rule for target.
max_ongoing_uac-x86_64-unknown-linux-gnu/fast:
	$(MAKE) -f link/libsip/test/max_ongoning_call_for_account/uac/CMakeFiles/max_ongoing_uac-x86_64-unknown-linux-gnu.dir/build.make link/libsip/test/max_ongoning_call_for_account/uac/CMakeFiles/max_ongoing_uac-x86_64-unknown-linux-gnu.dir/build
.PHONY : max_ongoing_uac-x86_64-unknown-linux-gnu/fast

#=============================================================================
# Target rules for targets named thread_test-x86_64-unknown-linux-gnu

# Build rule for target.
thread_test-x86_64-unknown-linux-gnu: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 thread_test-x86_64-unknown-linux-gnu
.PHONY : thread_test-x86_64-unknown-linux-gnu

# fast build rule for target.
thread_test-x86_64-unknown-linux-gnu/fast:
	$(MAKE) -f link/libsip/test/thread_test/CMakeFiles/thread_test-x86_64-unknown-linux-gnu.dir/build.make link/libsip/test/thread_test/CMakeFiles/thread_test-x86_64-unknown-linux-gnu.dir/build
.PHONY : thread_test-x86_64-unknown-linux-gnu/fast

#=============================================================================
# Target rules for targets named callee_hangup_uas-x86_64-unknown-linux-gnu

# Build rule for target.
callee_hangup_uas-x86_64-unknown-linux-gnu: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 callee_hangup_uas-x86_64-unknown-linux-gnu
.PHONY : callee_hangup_uas-x86_64-unknown-linux-gnu

# fast build rule for target.
callee_hangup_uas-x86_64-unknown-linux-gnu/fast:
	$(MAKE) -f link/libsip/test/uac_hangup_call/uas/CMakeFiles/callee_hangup_uas-x86_64-unknown-linux-gnu.dir/build.make link/libsip/test/uac_hangup_call/uas/CMakeFiles/callee_hangup_uas-x86_64-unknown-linux-gnu.dir/build
.PHONY : callee_hangup_uas-x86_64-unknown-linux-gnu/fast

#=============================================================================
# Target rules for targets named callee_hangup_uac-x86_64-unknown-linux-gnu

# Build rule for target.
callee_hangup_uac-x86_64-unknown-linux-gnu: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 callee_hangup_uac-x86_64-unknown-linux-gnu
.PHONY : callee_hangup_uac-x86_64-unknown-linux-gnu

# fast build rule for target.
callee_hangup_uac-x86_64-unknown-linux-gnu/fast:
	$(MAKE) -f link/libsip/test/uac_hangup_call/uac/CMakeFiles/callee_hangup_uac-x86_64-unknown-linux-gnu.dir/build.make link/libsip/test/uac_hangup_call/uac/CMakeFiles/callee_hangup_uac-x86_64-unknown-linux-gnu.dir/build
.PHONY : callee_hangup_uac-x86_64-unknown-linux-gnu/fast

#=============================================================================
# Target rules for targets named uas-x86_64-unknown-linux-gnu

# Build rule for target.
uas-x86_64-unknown-linux-gnu: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uas-x86_64-unknown-linux-gnu
.PHONY : uas-x86_64-unknown-linux-gnu

# fast build rule for target.
uas-x86_64-unknown-linux-gnu/fast:
	$(MAKE) -f link/libsip/test/uas_hangup_call/uas/CMakeFiles/uas-x86_64-unknown-linux-gnu.dir/build.make link/libsip/test/uas_hangup_call/uas/CMakeFiles/uas-x86_64-unknown-linux-gnu.dir/build
.PHONY : uas-x86_64-unknown-linux-gnu/fast

#=============================================================================
# Target rules for targets named uac-x86_64-unknown-linux-gnu

# Build rule for target.
uac-x86_64-unknown-linux-gnu: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uac-x86_64-unknown-linux-gnu
.PHONY : uac-x86_64-unknown-linux-gnu

# fast build rule for target.
uac-x86_64-unknown-linux-gnu/fast:
	$(MAKE) -f link/libsip/test/uas_hangup_call/uac/CMakeFiles/uac-x86_64-unknown-linux-gnu.dir/build.make link/libsip/test/uas_hangup_call/uac/CMakeFiles/uac-x86_64-unknown-linux-gnu.dir/build
.PHONY : uac-x86_64-unknown-linux-gnu/fast

#=============================================================================
# Target rules for targets named perf_test_uas-x86_64-unknown-linux-gnu

# Build rule for target.
perf_test_uas-x86_64-unknown-linux-gnu: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 perf_test_uas-x86_64-unknown-linux-gnu
.PHONY : perf_test_uas-x86_64-unknown-linux-gnu

# fast build rule for target.
perf_test_uas-x86_64-unknown-linux-gnu/fast:
	$(MAKE) -f link/libsip/test/perf_test/uas/CMakeFiles/perf_test_uas-x86_64-unknown-linux-gnu.dir/build.make link/libsip/test/perf_test/uas/CMakeFiles/perf_test_uas-x86_64-unknown-linux-gnu.dir/build
.PHONY : perf_test_uas-x86_64-unknown-linux-gnu/fast

#=============================================================================
# Target rules for targets named perf_test_uac-x86_64-unknown-linux-gnu

# Build rule for target.
perf_test_uac-x86_64-unknown-linux-gnu: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 perf_test_uac-x86_64-unknown-linux-gnu
.PHONY : perf_test_uac-x86_64-unknown-linux-gnu

# fast build rule for target.
perf_test_uac-x86_64-unknown-linux-gnu/fast:
	$(MAKE) -f link/libsip/test/perf_test/uac/CMakeFiles/perf_test_uac-x86_64-unknown-linux-gnu.dir/build.make link/libsip/test/perf_test/uac/CMakeFiles/perf_test_uac-x86_64-unknown-linux-gnu.dir/build
.PHONY : perf_test_uac-x86_64-unknown-linux-gnu/fast

#=============================================================================
# Target rules for targets named day_night_test_uas-x86_64-unknown-linux-gnu

# Build rule for target.
day_night_test_uas-x86_64-unknown-linux-gnu: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 day_night_test_uas-x86_64-unknown-linux-gnu
.PHONY : day_night_test_uas-x86_64-unknown-linux-gnu

# fast build rule for target.
day_night_test_uas-x86_64-unknown-linux-gnu/fast:
	$(MAKE) -f link/libsip/test/day_night_test/uas/CMakeFiles/day_night_test_uas-x86_64-unknown-linux-gnu.dir/build.make link/libsip/test/day_night_test/uas/CMakeFiles/day_night_test_uas-x86_64-unknown-linux-gnu.dir/build
.PHONY : day_night_test_uas-x86_64-unknown-linux-gnu/fast

#=============================================================================
# Target rules for targets named day_night_test_uac-x86_64-unknown-linux-gnu

# Build rule for target.
day_night_test_uac-x86_64-unknown-linux-gnu: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 day_night_test_uac-x86_64-unknown-linux-gnu
.PHONY : day_night_test_uac-x86_64-unknown-linux-gnu

# fast build rule for target.
day_night_test_uac-x86_64-unknown-linux-gnu/fast:
	$(MAKE) -f link/libsip/test/day_night_test/uac/CMakeFiles/day_night_test_uac-x86_64-unknown-linux-gnu.dir/build.make link/libsip/test/day_night_test/uac/CMakeFiles/day_night_test_uac-x86_64-unknown-linux-gnu.dir/build
.PHONY : day_night_test_uac-x86_64-unknown-linux-gnu/fast

#=============================================================================
# Target rules for targets named mqtt_dy-x86_64-unknown-linux-gnu

# Build rule for target.
mqtt_dy-x86_64-unknown-linux-gnu: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mqtt_dy-x86_64-unknown-linux-gnu
.PHONY : mqtt_dy-x86_64-unknown-linux-gnu

# fast build rule for target.
mqtt_dy-x86_64-unknown-linux-gnu/fast:
	$(MAKE) -f link/libmqtt/CMakeFiles/mqtt_dy-x86_64-unknown-linux-gnu.dir/build.make link/libmqtt/CMakeFiles/mqtt_dy-x86_64-unknown-linux-gnu.dir/build
.PHONY : mqtt_dy-x86_64-unknown-linux-gnu/fast

#=============================================================================
# Target rules for targets named mqtt-x86_64-unknown-linux-gnu

# Build rule for target.
mqtt-x86_64-unknown-linux-gnu: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mqtt-x86_64-unknown-linux-gnu
.PHONY : mqtt-x86_64-unknown-linux-gnu

# fast build rule for target.
mqtt-x86_64-unknown-linux-gnu/fast:
	$(MAKE) -f link/libmqtt/CMakeFiles/mqtt-x86_64-unknown-linux-gnu.dir/build.make link/libmqtt/CMakeFiles/mqtt-x86_64-unknown-linux-gnu.dir/build
.PHONY : mqtt-x86_64-unknown-linux-gnu/fast

#=============================================================================
# Target rules for targets named mos_test-x86_64-unknown-linux-gnu

# Build rule for target.
mos_test-x86_64-unknown-linux-gnu: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mos_test-x86_64-unknown-linux-gnu
.PHONY : mos_test-x86_64-unknown-linux-gnu

# fast build rule for target.
mos_test-x86_64-unknown-linux-gnu/fast:
	$(MAKE) -f link/libmqtt/test/CMakeFiles/mos_test-x86_64-unknown-linux-gnu.dir/build.make link/libmqtt/test/CMakeFiles/mos_test-x86_64-unknown-linux-gnu.dir/build
.PHONY : mos_test-x86_64-unknown-linux-gnu/fast

#=============================================================================
# Target rules for targets named sdk-x86_64-unknown-linux-gnu

# Build rule for target.
sdk-x86_64-unknown-linux-gnu: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sdk-x86_64-unknown-linux-gnu
.PHONY : sdk-x86_64-unknown-linux-gnu

# fast build rule for target.
sdk-x86_64-unknown-linux-gnu/fast:
	$(MAKE) -f link/libsdk/CMakeFiles/sdk-x86_64-unknown-linux-gnu.dir/build.make link/libsdk/CMakeFiles/sdk-x86_64-unknown-linux-gnu.dir/build
.PHONY : sdk-x86_64-unknown-linux-gnu/fast

#=============================================================================
# Target rules for targets named testupload

# Build rule for target.
testupload: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 testupload
.PHONY : testupload

# fast build rule for target.
testupload/fast:
	$(MAKE) -f link/libtsuploader/CMakeFiles/testupload.dir/build.make link/libtsuploader/CMakeFiles/testupload.dir/build
.PHONY : testupload/fast

#=============================================================================
# Target rules for targets named tsuploader

# Build rule for target.
tsuploader: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tsuploader
.PHONY : tsuploader

# fast build rule for target.
tsuploader/fast:
	$(MAKE) -f link/libtsuploader/CMakeFiles/tsuploader.dir/build.make link/libtsuploader/CMakeFiles/tsuploader.dir/build
.PHONY : tsuploader/fast

#=============================================================================
# Target rules for targets named qiniu

# Build rule for target.
qiniu: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 qiniu
.PHONY : qiniu

# fast build rule for target.
qiniu/fast:
	$(MAKE) -f link/libtsuploader/c-sdk/CMakeFiles/qiniu.dir/build.make link/libtsuploader/c-sdk/CMakeFiles/qiniu.dir/build
.PHONY : qiniu/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... ffmpeg"
	@echo "... curl-7.61.0"
	@echo "... pjsip"
	@echo "... vod"
	@echo "... sip-x86_64-unknown-linux-gnu"
	@echo "... max_account-x86_64-unknown-linux-gnu"
	@echo "... max_call_uas-x86_64-unknown-linux-gnu"
	@echo "... max_call_uac-x86_64-unknown-linux-gnu"
	@echo "... max_ongoing_uas"
	@echo "... max_ongoing_uac-x86_64-unknown-linux-gnu"
	@echo "... thread_test-x86_64-unknown-linux-gnu"
	@echo "... callee_hangup_uas-x86_64-unknown-linux-gnu"
	@echo "... callee_hangup_uac-x86_64-unknown-linux-gnu"
	@echo "... uas-x86_64-unknown-linux-gnu"
	@echo "... uac-x86_64-unknown-linux-gnu"
	@echo "... perf_test_uas-x86_64-unknown-linux-gnu"
	@echo "... perf_test_uac-x86_64-unknown-linux-gnu"
	@echo "... day_night_test_uas-x86_64-unknown-linux-gnu"
	@echo "... day_night_test_uac-x86_64-unknown-linux-gnu"
	@echo "... mqtt_dy-x86_64-unknown-linux-gnu"
	@echo "... mqtt-x86_64-unknown-linux-gnu"
	@echo "... mos_test-x86_64-unknown-linux-gnu"
	@echo "... sdk-x86_64-unknown-linux-gnu"
	@echo "... testupload"
	@echo "... tsuploader"
	@echo "... qiniu"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

